### ISSUE TITLE
orderservice

### ISSUE THREAD

**Issue by AniSkyWorker** [luchininaanna/go-course#1]
- [x] в order.go можно не экспортировать сущности(не писать с большой буквы), т.к. кроме этого пакета они нигде не используются
- [x] если будет ошибка при записи response в io.WriteString, то вернём 200 или вообще упадём

**Comment by luchininaanna** [comment]
1. В следующей лабораторной (подключение базы данных к сервису) данные сущности уже используются в других пакетах, поэтому поправить не получится
* примеры такого кода уже в репозитории есть
